export const datosInicio = {
    version: 'V0.00068',
    ambiente : 'Producción', // Realmente no es "Producción" es "Servidor Vesta" para diferenciarlo de localhost (LAMPP)
    pruebas: 'No', 
    indicador_ambiente_dev : 1, // 1 = Desarrollo, 0 = Producción 
    // endpoint : 'https://ofiliaria.com.uy/public/api/v1', 
    endpoint : 'https://dev2.ofiliaria.com/user/garantias', 

    url_almacenamiento : '',
    usuario_administrador : 'No',
    inicio_ruta: '/user/',
    agencia_id : 0,
    agente_id : 0,
    rol_usuario_conectado : 0,
    tipo_agencia_agente : 'estate_agency',
    token_laravel : '', // Eliminar cuando se termine la migración
    garantia_id : 0,
    aseguradora : '',
    propiedad_id : 0,
    numero_identidad_propiedad : '',
    nombre_propiedad : '',
    direccion_propiedad : '',
    tipo_propiedad : '',
    tasa_cambio: 0,
    moneda_propiedad : '',
    costo_alquiler : 0,
    costo_alquiler_pruebas : 0,
    cantidad_personas_adicionales : 0,
    agregando_persona : false,
    editando_persona : false,
    persona_eliminada : false,
    id : 0,
    tipo_arrendatario: null, 
    tipo_persona : '',
    tipo_documento_identidad : '',
    numero_identidad_arrendatario : '',
    nombres_arrendatario : '',
    apellidos_arrendatario : '',
    numero_identidad_empresa : '',
    empresa : '',
    cargo_empresa : '',
    email_arrendatario : '',
    telefono_arrendatario : '',
    moneda_ingreso : '',
    monto_ingreso: 0,
    ingreso: '',
    sueldo : '',
    
    identidad : null,
    etiqueta_identidad : null,
    ubicacion_identidad : null,
    contador_identidad : 0,
    
    rec_sueldo : null,
    etiqueta_rec_sueldo : null,
    ubicaciones_rec_sueldo : null,
    contador_rec_sueldo : 0,
    
    cert_ing_mod : null,
    etiqueta_cert_ing_mod : null,
    ubicaciones_cert_ing_mod : null,
    contador_cert_ing_mod : 0,
    
    dgi : null,
    etiqueta_dgi : null,
    ubicaciones_dgi : null,
    contador_dgi : 0,
    
    cert_dgi_caja : null,
    etiqueta_cert_dgi_caja : null,
    ubicaciones_cert_dgi_caja : null,
    contador_cert_dgi_caja : 0,

    balance : null,
    etiqueta_balance : null,
    ubicaciones_balance : null,
    contador_balance : 0,

    rut : null,
    etiqueta_rut : null,
    ubicaciones_rut : null,
    contador_rut : 0,

    contrato_social : null,
    etiqueta_contrato_social : null,
    ubicaciones_contrato_social : null,
    contador_contrato_social : 0,

    cert_uni : null,
    etiqueta_cert_uni : null,
    ubicaciones_cert_uni : null,
    contador_cert_uni : 0,

    domicilio_persona : '',
    departamento_domicilio : '',
    ciudad_domicilio : '',
    clasificacion_persona_fisica : '',
    clasificacion_persona_juridica : '',
    notas_persona : '',

    personas : null,
    paso_anterior : null,
    paso_siguiente: null,
    titulo_formulario : 'Datos del arrendatario (inquilino)',
    limite_pago : 0,
    faltante : 0,
    edicion_garantia : false,
    archivos_base64 : null,
    conversion_archivos : false,
    propiedad_registrada : null,
    estatus_garantia : null,
    estatus_registro : 'Activo',
    en_revision : false,
    aprobacion_garantia : '',
    mostrar_modal_ingresos_suficientes : false,
    titulo_correo : 'Solicitud de revisión de garantias',
    cantidad_propietarios : 3,
    estatus_garantia_adicional : '',
    inputs_aseguradoras : '',
    tipo_contrato : '',
    fecha_inicio_alquiler : '',
    plazo_alquiler : '',
    tipo_plazo_alquiler : '',
    tipo_pago_alquiler : '',
    regimen_ajuste_alquiler : '',
    departamento_firma : '',
    ciudad_firma : '',
    terminos_condiciones : '',
    banco : '',
    numero_sucursal_banco : '',
    nombres_titular_cuenta : '',
    apellidos_titular_cuenta : '',
    moneda : '',
    numero_cuenta : '',
    tipo_cuenta : '',
    texto_contrato : '',
    notas_garantia : '',
    correo_notificaciones : '',
    tipo_inventario : '',
    descripcion_inventario : '',
    observaciones_inventario : '',
    archivos_inventario_base64 : null,
    
    contrato : null,
    ubicaciones_contrato : null,

    archivos_inventario : null,
    etiqueta_inventario : null,
    ubicaciones_inventario : null,
    contador_inventario : 0,
        
    foto_inventario : null,
    ubicaciones_foto_inventario : null,
    
    contrato_firmado_base64 : null,
    contrato_firmado : null,
    etiqueta_contrato_firmado : null,
    ubicaciones_contrato_firmado : null,
    contador_contrato_firmado : 0,
    
    inventario_firmado : null,
    etiqueta_inventario_firmado : null,
    ubicaciones_inventario_firmado : null,
    contador_inventario_firmado : 0,
    
    formulario_firmado : null,
    etiqueta_formulario_firmado : null,
    ubicaciones_formulario_firmado : null,
    contador_formulario_firmado : 0,

    comprobante_pago : null,
    etiqueta_comprobante_pago : null,
    ubicaciones_comprobante_pago : null,
    contador_comprobante_pago : 0
};