import { generarClausulaAdicional } from './contratoUtils';

export const ContratoSancor = ({ datosContrato }) => {

  const numeroALetras = (num) => {
    const unidades = ["", "un", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve"];
    if (num >= 1 && num <= 9) {
      return unidades[num];
    }
    return num;
  };

  const clausulaAdicional = generarClausulaAdicional(datosContrato.terminos_condiciones, 13);

  return (
      <>
      <h3>CONTRATO DE ARRENDAMIENTO</h3>
      
      <p>En {datosContrato.ciudad_firma}, a los {datosContrato.fecha_inicio_alquiler_desglosada.diaLetras} días del mes de {datosContrato.fecha_inicio_alquiler_desglosada.mesLetras} de {datosContrato.fecha_inicio_alquiler_desglosada.anio}, Por una parte: {datosContrato.texto_arrendador}, en su calidad de arrendador(es), y por otra parte: {datosContrato.texto_arrendatario}, en su calidad de arrendatario(s), con domicilio constituido en la finca arrendada sita en {datosContrato.direccion_propiedad}, convienen celebrar el presente contrato de arrendamiento que se regirá por los siguientes términos:</p>
      
      <p>PRIMERO: Objeto. La parte Arrendadora da y la parte Arrendataria toma en arrendamiento el inmueble de propiedad de la primera, en el estado que se detalla en el Inventario que las partes suscribirán en el momento de la ocupación y que forma parte del presente contrato.</p> 
      
      <p>SEGUNDO: Plazo. El plazo de este contrato se fija en {numeroALetras(datosContrato.plazo_alquiler)} ({datosContrato.plazo_alquiler}) {datosContrato.plazo_alquiler > 1 ? datosContrato.tipo_plazo_alquiler : datosContrato.tipo_plazo_alquiler.slice(0, -1)} contados a partir de el(los) {datosContrato.fecha_inicio_alquiler_desglosada.diaLetras} días del mes de {datosContrato.fecha_inicio_alquiler_desglosada.mesLetras} de {datosContrato.fecha_inicio_alquiler_desglosada.anio} con opción de prorrogar su vigencia por el plazo de {numeroALetras(datosContrato.plazo_alquiler)} ({datosContrato.plazo_alquiler}) {datosContrato.plazo_alquiler > 1 ? datosContrato.tipo_plazo_alquiler : datosContrato.tipo_plazo_alquiler.slice(0, -1)} más.</p> 
      
      <p>TERCERO: Precio. El precio del arrendamiento se pacta en la suma de {datosContrato.costo_alquiler+' '+datosContrato.moneda_propiedad} mensuales, pagaderos dentro de los primeros 10 días de cada mes por deposito en el Banco {datosContrato.banco}, cuenta {datosContrato.numero_cuenta}, a nombre de {datosContrato.nombres_titular_cuenta+' '+datosContrato.apellidos_titular_cuenta}. Se abona en este acto el precio correspondiente al primer mes de arrendamiento, constituyendo el presente contrato formal carta de pago, siendo de cargo de la parte arrendataria el pago de los gastos comunes correspondientes a la referida unidad objeto de este arredramiento. En caso de que la parte arrendataria hiciera uso de la opción de prórroga prevista en la cláusula anterior, el precio se verá incrementado de acuerdo al IPC.</p>
      
      <p>CUARTO: Destino. El destino del inmueble arrendado será de casa habitación para la parte Arrendataria, su familia y personas a su cargo. Le queda expresamente prohibido a la parte Arrendataria variar el destino establecido, así como ceder o subarrendar total o parcialmente el inmueble arrendado sin la previa autorización por escrito de la Arrendadora. Cualquier contravención a lo aquí acordado, en forma total o parcial y sea cual fuere su entidad, dará mérito suficiente a la rescisión de este Contrato, debiéndose en este caso abonar como multa el total de las rentas que faltaren hasta cumplirse la totalidad del plazo del arrendamiento.</p>
      
      <p>QUINTO: Obligaciones de la Arrendataria. La Arrendataria se obliga especialmente a: a) abonar puntualmente los alquileres; b) abonar los consumos de los distintos servicios que existieren en el inmueble (agua, gas, electricidad, etc.) obligándose a efectuar el cambio de titularidad a su nombre de todos ellos y a devolverlos en su estado original una vez finalizado el contrato, así como abonar los Tributos Domiciliarios municipales o cualquier otro que le correspondiere en su calidad, hasta el momento en que desocupe el inmueble. Si por cualquier circunstancia se abonaran por la Arrendadora, deberá procederse a su restitución, conjuntamente con el alquiler mensual, debiendo satisfacer, asimismo, los recargos, sanciones, intereses, costas y costos que correspondan en su caso. El pago de la Contribución Inmobiliaria, Impuesto a Primaria y otros a crearse, que graven la propiedad serán de cargo de la arrendadora: c) mantener el bien y sus instalaciones en buen estado de conservación, siendo de su cargo y cuenta la limpieza y desobstrucción de desagües: d) restituir el bien en el mismo estado en que lo recibe, salvo el deterioro causado por el uso legítimo; e) 60 días antes de vencer el Contrato o su eventual prórroga, permitir la visita al inmueble de los interesados en arrendarlo. Las visitas deberán realizarse en días y horas hábiles que no afecten el descanso ni la tranquilidad de la Arrendataria y su familia previa coordinación con la Arrendadora; f) permitir previa coordinación con el Arrendataría: la realización de los trabajos necesarios o convenientes para la conservación o mejora de la finca, sin derecho a indemnización o erogación a su favor, admitiendo el acceso de profesionales, técnicos, operarios o interesados a los efectos previstos y el ingreso de materiales y herramientas necesarios; g) no realizar actividades que perjudiquen el bien o causen ruidos molestos que alteren la pacífica convivencia del vecindario o alteren el orden público. h) Al momento de la restitución del inmueble, la parte Arrendataria deberá entregar a la Arrendadora los últimos recibos de pago de todos los servicios, consumos e impuestos que se mencionan en el presente Contrato.</p>
      
      <p>SEXTO: Prohibiciones. Cualquier construcción, obra, mejora o trabajo que la Arrendataria realizare en el bien arrendado, no podrá ser levantada, removida o separada sin el consentimiento dado por escrito por la Arrendadora y efectuadas las mismas, la Arrendadora no estará obligada a pagar indemnización o compensación de ninguna especie. En caso de ser dichas obras realizadas sin consentimiento de la Arrendadora, a opción de la Arrendadora podrán ser quitadas o quedarán en todo caso en beneficio de la propiedad, sin perjuicio de las acciones que correspondan por el incumplimiento de la Arrendataria, si aquellas fueren ejecutadas sin sujeción  a las ordenanzas municipales y de previsión social. No obstante, la Arrendadora queda en libertad de no aceptar las reformas y mejoras incorporadas, en cuyo caso podrá exigir que la Arrendataria devuelva la finca a su estado original, sin perjuicio de que si no lo hiciere antes de restituir la finca a la Arrendadora, mande realizar las obras necesarias a costa de la Arrendataria.</p>
      
      <p>SÉPTIMO: Responsabilidades. A) Los efectos, suspensiones o interrupciones en los servicios de agua, energía y demás consumos de la finca, no imputables a la Arrendadora en modo alguno eximirán a la Arrendataria del puntual y exacto cumplimiento de las obligaciones a su cargo; b)La Arrendadora en ningún caso tendrá responsabilidad cuando el origen de las deficiencias provenga de fallas o defectos en el suministro o en las cañerías o conductores externos de la finca, siempre que los mismos sean responsabilidad de las entidades prestadoras del servicio; c) la Arrendataria exonera a la Arrendadora de toda responsabilidad por daños y perjuicios o accidentes que ocurran en los servicios de agua, gas, energía eléctrica, cañerías o similares o deriven o se relacionen con los mismos y se originen por interrupciones, falta de regularidad o cualquier otra causa: d) será de cargo de la Arrendadora la realización de las reparaciones necesarias o convenientes para la conservación de la propiedad o aquellas que le permitan a la Arrendataria la continuidad del arrendamiento en las condiciones en que se recibió la finca, salvo que la mal conservación o funcionamiento de los servicios se deban al descuido o negligencia de esta última. En el caso que se detectaran en el bien arrendado defectos, suspensiones o interrupciones imputables a la propiedad que impidan su uso normal o su habitabilidad normal, que no hubieren sido detectados en el momento de la ocupación, la Arrendataria comunicará a la Arrendadora el hecho, tan pronto como sea posible, debiendo la Arrendadora tomar todas las medidas necesarias razonables para reparare el o los defectos en tiempo oportuno, de acuerdo a la urgencia que amerite cada situación.</p> 
      
      <p>OCTAVO. Garantía. Los posibles incumplimientos al presente contrato, estarán garantizados por póliza de Garantía de Alquiler de Sancor Seguros SA, cuyas condiciones de cobertura han sido aceptadas por los firmantes. La entrega de llaves se hará efectiva a partir de que el arrendatario presente ante la administradora la póliza original correspondiente o el pago correspondiente al premio que esta genere. Son de conocimiento del Arrendador y Arrendatario/s las condiciones generales y particulares del seguro. El/Los Arrendatarios devolverá/n el inmueble totalmente desocupado de personas y cosas y en el mismo estado en que lo recibe/n del arrendador, haciendo entrega de llaves contra recibo escrito de éste último, previa realización de inspección ocular e inventario para constatar el estado de la finca y los desperfectos que tuviere. Las partes convienen expresamente que si al momento de realizarse el lanzamiento de la finca arrendada existieren dentro de la misma bienes muebles y/o inmuebles por accesión, los mismos se considerarán irrevocablemente abandonados a favor del arrendador, quien podrá ejercer cualquiera de las facultades establecidas en el artículo 487 del Código Civil, sin responsabilidad de especie alguna. Las partes acuerdan firmar la rescisión del presente contrato, aun cuando ésta se realice al final del plazo contractual, y simultáneamente solicitar la cancelación de la póliza de alquiler con la mencionada documentación en oficinas del Asegurador.</p>
      
      <p>NOVENO. De la Mora, Incumplimiento y Rescisión. Las partes caerán en mora de pleno derecho, sin necesidad de interpelación judicial o extrajudicial de especie alguna, por el solo vencimiento de los plazos o por dar, hacer o no hacer cualquier acto o hecho contrario a lo aquí estipulado. La falta de cumplimiento de cualquiera de las partes a las obligaciones contraídas en este documento, dará derecho a la otra a solicitar a su voluntad la resolución del mismo o a exigir su cumplimiento, siendo en ambos casos los tributos, costos, daños y perjuicios que se ocasionaren, de cargo de la parte incumplidora. En caso de no abonar con puntualidad los alquileres estos devengarán el interés de mora de plaza autorizado por el Banco Central del Uruguay.</p>
      
      <p>DÉCIMO. Entrega de la finca. Antes de vencer el plazo contractual, la Arrendataria comunicará a la Arrendadora, con una antelación de 60 (sesenta) días por lo menos, su voluntad de entregar el inmueble, estableciendo posteriormente y de común acuerdo con la Arrendadora, el día y hora para la realización del Inventario, acreditar el pago de sus obligaciones y hacer entrega desocupada de la vivienda. En el acto de entrega se verificará el estado del inmueble con el inventario y se dejará constancia de los desperfectos que hubiere, así como de los gastos, consumos y adeudos impagos y se procederá a abonar los mismos. En caso de existir desacuerdo entre las partes respecto de la evaluación de los mismos, se designará un árbitro de común acuerdo entre las partes, aceptando en forma obligatoria la estimación que dicha persona realice. Si alguna de las partes no cumpliera con la obligación antes referida de nombrar perito, se considerará aceptado el inventario y tasación de los desperfectos o deterioros practicados por la otra parte. En todos los casos, el Arrendatario deberá hacer efectiva la cantidad correspondiente a los deterioros o desperfectos a que se hace mención en el apartado anterior. La deuda a tal respecto se reputará indivisible con el alquiler, y su falta de pago tendrá iguales efectos que la del propio alquiler.</p>
      
      {
        datosContrato.regimen_ajuste_alquiler == 'Contrato regido por ley 14.219 (permiso de construcción anterior al 02/06/68)' ?
        <p>UNDÉCIMO: La finca tiene permiso de construcción anterior a 1968, por ende, se rige por la ley 14.219</p> :
        <p>UNDÉCIMO: La finca tiene permiso de construcción posterior a 1968, por ende, se rige por el régimen de libre contratación.</p> 
      } 
      
      <p>DÉCIMO SEGUNDO. Declaraciones. La Arrendataria declara: a) haber examinado el inmueble y lo recibe a entera satisfacción en el estado que presenta; b) que el inmueble es apto para servir al destino para el cual se arrienda; c) que el inmueble se encuentra en perfecto estado de conservación y funcionamiento comprometiéndose a devolverlo en igual estado, salvo aquellos deterioros que se produjeren por la acción del tiempo conforme a un uso legítimo y moderado. PARA CONSTANCIA SE FIRMAN TRES EJEMPLARES DE UN MISMO TENOR, PARA CADA UNA DE LAS PARTES, EN EL LUGAR Y FECHA INDICADOS EN LA COMPARECENCIA.</p>

      <div dangerouslySetInnerHTML={{ __html: clausulaAdicional }} />

      <p>Parte Arrendadora: __________________</p>

      <p>Parte Arrendadora: __________________</p>
      <br />
      <br />
      <p>Parte Arrendataria: __________________</p>

      <p>Parte Arrendataria: __________________</p>
      </>
  );
}